title: <p align="center"> Ishwar Madavi </p>
logo: /assets/img/passport_size_pic.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/ishwar-madavi/">LinkedIn</a> |
  
  <br>   
  I have 4 years of experience as Full Stack Developer.
  I have experience on tech stacks like JAVA, Angular, HTML, CSS, Spring Boot.
  <br>
  </p>



theme: jekyll-theme-minimal
